# Generated by Django 5.0.6 on 2024-07-19 04:37

import admission.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0004_alter_monthlysubjectsyllabusstatus_annual_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.CharField(editable=False, max_length=6, verbose_name=admission.models.shortuuid)),
                ('admission_id', models.CharField(default=admission.models.shortuuid, max_length=6, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=50)),
                ('guardian_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('profile_image', models.ImageField(blank=True, default='admission_images/default_profile.png', null=True, upload_to='admission_images/')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('mobile_number', models.CharField(max_length=12)),
                ('aadhar_number', models.CharField(max_length=12, unique=True)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('date_of_admission', models.DateField()),
                ('previous_result_status', models.CharField(choices=[('pass', 'PASS'), ('fail', 'FAIL')], default='pass', max_length=10)),
                ('previous_institution', models.CharField(max_length=200)),
                ('previous_education', models.CharField(max_length=200)),
                ('school_education', models.CharField(max_length=200)),
                ('lc_given', models.BooleanField(default=False)),
                ('pay_fees', models.BooleanField(default=False)),
                ('fees_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('required_donation', models.BooleanField(default=False)),
                ('admission_status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('left', 'Left')], default='pending', max_length=50)),
                ('applied_for', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='academic.course')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admission.admission')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
