# Generated by Django 5.0.4 on 2024-05-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='admission_images/'),
        ),
    ]
