# Generated by Django 5.0.6 on 2024-06-30 17:49

import admission.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_alter_monthlysubjectsyllabusstatus_annual_status_and_more'),
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherDetails',
            fields=[
                ('other_id', models.CharField(default=admission.models.shortuuid, max_length=6, primary_key=True, serialize=False)),
                ('pay_fees', models.BooleanField(default=False)),
                ('fees_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('required_donation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('personal_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=200)),
                ('guardian_name', models.CharField(max_length=40)),
                ('date_of_birth', models.DateField()),
                ('profile_image', models.ImageField(blank=True, default='admission_images/default_profile.png', null=True, upload_to='admission_images/')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('mobile_number', models.CharField(max_length=12)),
                ('aadhar_number', models.CharField(max_length=12, unique=True)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('date_of_admission', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='admission',
        ),
        migrations.CreateModel(
            name='AcademicDetails',
            fields=[
                ('academic_id', models.CharField(default=admission.models.shortuuid, max_length=6, primary_key=True, serialize=False)),
                ('previous_result_status', models.CharField(choices=[('pass', 'PASS'), ('fail', 'FAIL')], default='pass', max_length=10)),
                ('previous_institution', models.CharField(max_length=200)),
                ('previous_education', models.CharField(max_length=200)),
                ('school_education', models.CharField(max_length=200)),
                ('lc_given', models.BooleanField(default=False)),
                ('applied_for', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='academic.course')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionForm',
            fields=[
                ('admission_id', models.CharField(default=admission.models.shortuuid, max_length=6, primary_key=True, serialize=False)),
                ('admission_status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('left', 'Left'), ('graduated', 'Graduated')], default='pending', max_length=50)),
                ('academic_details', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='admission.academicdetails')),
                ('other_details', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='admission.otherdetails')),
                ('personal_details', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='admission.personaldetails')),
            ],
        ),
        migrations.DeleteModel(
            name='Admission',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
