# Generated by Django 5.0.4 on 2024-09-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='updated_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
