# Generated by Django 5.0.4 on 2024-05-01 20:23

import admission.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='admission_id',
            field=models.CharField(editable=False, max_length=6, verbose_name=admission.models.shortuuid),
        ),
    ]
