# Generated by Django 5.0.4 on 2024-05-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_alter_admission_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='profile_image',
            field=models.ImageField(blank=True, default='admission_images/default_profile.png', null=True, upload_to='admission_images/'),
        ),
    ]
