# Generated by Django 5.0.4 on 2024-05-01 20:33

import admission.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_alter_admission_admission_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('admission_id', models.CharField(editable=False, max_length=6, verbose_name=admission.models.shortuuid)),
                ('student_name', models.CharField(max_length=200)),
                ('guardian_name', models.CharField(max_length=40)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('applied_for', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('state', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('mobile_number', models.CharField(max_length=12)),
                ('addhar_number', models.CharField(max_length=12, unique=True)),
                ('previous_result_status', models.CharField(choices=[('pass', 'PASS'), ('fail', 'FAIL')], default='1', max_length=10)),
                ('addmission_status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('left', 'Left'), ('graduated', 'Graduated')], default='1', max_length=50)),
                ('previous_institution', models.CharField(max_length=200)),
                ('worldly_studies', models.CharField(max_length=200)),
                ('previous_education', models.CharField(blank=True, max_length=100, null=True)),
                ('school_studies', models.CharField(max_length=100)),
                ('lc_given', models.BooleanField(default=False)),
                ('donation', models.BooleanField(default=False)),
                ('donation_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('require_donation', models.BooleanField(default=False)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('date_of_admisson', models.DateField()),
            ],
        ),
    ]
