# Generated by Django 5.0.4 on 2024-05-01 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
