# Generated by Django 5.0.4 on 2024-05-01 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=200)),
                ('guardian_name', models.CharField(max_length=40)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='admission.admission')),
            ],
        ),
    ]
