# Generated by Django 5.0.4 on 2024-05-01 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='addmission_status',
            new_name='admission_status',
        ),
    ]
