# Generated by Django 5.0.4 on 2024-05-01 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0006_rename_addmission_status_admission_admission_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='guardian_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_name',
        ),
    ]
