# Generated by Django 5.0.4 on 2024-07-27 19:14

import django.db.models.deletion
import examination.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('exam_type_id', models.CharField(default=examination.models.shortuuid, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('effective_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ExamTimeTable',
            fields=[
                ('exam_time_table_id', models.CharField(default=examination.models.shortuuid, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('total_marks', models.PositiveIntegerField()),
                ('passing_marks', models.PositiveIntegerField()),
                ('time', models.TimeField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.student')),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.examtype')),
            ],
        ),
        migrations.CreateModel(
            name='HallTicket',
            fields=[
                ('hall_ticket_number', models.CharField(default=examination.models.shortuuid, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('exam_time_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.examtimetable')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.student')),
            ],
        ),
        migrations.CreateModel(
            name='MarkSheet',
            fields=[
                ('mark_sheet_id', models.CharField(default=examination.models.shortuuid, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('marks_obtained', models.PositiveIntegerField()),
                ('result', models.CharField(editable=False, max_length=20)),
                ('exam_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.examtimetable')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.student')),
            ],
        ),
        migrations.CreateModel(
            name='ResultSheet',
            fields=[
                ('result_sheet_id', models.CharField(default=examination.models.shortuuid, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('result_data', models.JSONField()),
                ('total_marks_obtained', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.student')),
            ],
        ),
    ]
