# Generated by Django 5.1 on 2024-08-19 17:59

import attendance.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FingerRecord',
            fields=[
                ('record_id', models.CharField(default=attendance.models.shortuuid, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('fingerprint_data', models.BinaryField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.CharField(default=attendance.models.shortuuid, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.student')),
                ('time_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.timetable')),
            ],
            options={
                'unique_together': {('time_table', 'student', 'date')},
            },
        ),
    ]
