# Generated by Django 5.0.4 on 2024-09-03 17:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_alter_admission_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='date_of_admission',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
