# Generated by Django 5.0.4 on 2024-09-04 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_alter_admission_date_of_admission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='date_of_admission',
            field=models.DateField(default=datetime.datetime(2024, 9, 4, 16, 45, 22, 10807, tzinfo=datetime.timezone.utc)),
        ),
    ]
