# Generated by Django 5.0.4 on 2024-09-06 02:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_alter_admission_date_of_admission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='date_of_admission',
            field=models.DateField(default=datetime.datetime(2024, 9, 6, 2, 22, 17, 684758, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='admission',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
