# Generated by Django 5.0.4 on 2025-02-05 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_alter_admission_date_of_admission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='date_of_admission',
            field=models.DateField(default=datetime.datetime(2025, 2, 5, 16, 24, 26, 293721, tzinfo=datetime.timezone.utc)),
        ),
    ]
