# Generated by Django 5.0.4 on 2024-05-01 20:08

import django.db.models.deletion
import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('grade_id', models.CharField(max_length=6, unique=True, verbose_name=students.models.shortuuid)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('student_id', models.CharField(max_length=6, verbose_name=students.models.shortuuid)),
                ('name', models.CharField(max_length=200)),
                ('class_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('adhar_no', models.CharField(max_length=12, unique=True)),
                ('date_of_admission', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photos')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('teacher_id', models.CharField(max_length=6, verbose_name=students.models.shortuuid)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('graduated_from', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('academic_details', models.TextField()),
                ('joining_date', models.DateField()),
                ('grade_incharge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='students.grade')),
            ],
        ),
    ]
