# Generated by Django 5.0.4 on 2024-05-01 20:13

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade_id',
            field=models.CharField(editable=False, max_length=6, unique=True, verbose_name=students.models.shortuuid),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(editable=False, max_length=6, verbose_name=students.models.shortuuid),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='teacher_id',
            field=models.CharField(editable=False, max_length=6, verbose_name=students.models.shortuuid),
        ),
    ]
