# Generated by Django 5.0.4 on 2024-05-01 20:23

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_grade_grade_id_alter_studentprofile_student_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('student_detail_id', models.CharField(max_length=6, verbose_name=students.models.shortuuid)),
            ],
        ),
    ]
