# Generated by Django 5.0.4 on 2024-05-12 09:38

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_grade_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade_id',
            field=models.CharField(editable=False, max_length=6, verbose_name=students.models.shortuuid),
        ),
    ]
