# Generated by Django 5.0.4 on 2024-04-26 19:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
