# Generated by Django 5.0.4 on 2024-04-26 19:32

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default=students.models.shortuuid, editable=False, max_length=6, primary_key=True, serialize=False),
        ),
    ]
