# Generated by Django 5.0.4 on 2024-05-22 17:16

import academic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.CharField(editable=False, max_length=6, verbose_name=academic.models.shortuuid)),
                ('subject_code', models.CharField(default=academic.models.subject_custom_id, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=70)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
    ]
