# Generated by Django 5.0.4 on 2024-07-14 05:55

import academic.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnuallySubjectSyllabusStatus',
            fields=[
                ('annual_status_id', models.CharField(default=academic.models.shortuuid, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('teacher', models.CharField(max_length=20)),
                ('yearly_status', models.IntegerField()),
                ('yearly_summary', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.CharField(default=academic.models.shortuuid, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='SyllabusType',
            fields=[
                ('type_id', models.CharField(default=academic.models.shortuuid, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(default=academic.models.shortuuid, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('effective_date', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.department')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlySubjectSyllabusStatus',
            fields=[
                ('month_status_id', models.CharField(default=academic.models.shortuuid, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('month', models.DateField()),
                ('count', models.IntegerField(default=0)),
                ('monthly_summary', models.CharField(max_length=300)),
                ('annual_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.annuallysubjectsyllabusstatus')),
                ('target_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.syllabustype')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.CharField(default=academic.models.shortuuid, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('syllabus_count', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.course')),
                ('syllabus_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.syllabustype')),
            ],
        ),
        migrations.AddField(
            model_name='annuallysubjectsyllabusstatus',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.subject'),
        ),
        migrations.CreateModel(
            name='SyllabusStatusVerification',
            fields=[
                ('status_verification_id', models.CharField(default=academic.models.shortuuid, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('feedback', models.TextField(blank=True, max_length=300, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_date', models.DateTimeField()),
                ('monthly_syllabus_approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.monthlysubjectsyllabusstatus')),
            ],
        ),
    ]
