# Generated by Django 5.0.4 on 2024-05-22 17:20

import academic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(default=academic.models.subject_custom_id, editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
