# Generated by Django 5.0.4 on 2024-07-23 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysubjectsyllabusstatus',
            name='annual_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_statuses', to='academic.annuallysubjectsyllabusstatus'),
        ),
    ]
