# Generated by Django 5.0.6 on 2024-06-29 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_code',
        ),
        migrations.RemoveField(
            model_name='department',
            name='department_code',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_code',
        ),
    ]
