# Generated by Django 5.0.4 on 2024-05-25 13:08

import academic.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_alter_subject_subject_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.CharField(default=academic.models.shortuuid, editable=False, max_length=6)),
                ('department_code', models.CharField(default=academic.models.department_custom_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(default=academic.models.subject_custom_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_id',
            field=models.CharField(default=academic.models.shortuuid, editable=False, max_length=6),
        ),
        migrations.CreateModel(
            name='AnnuallySubjectSyllabusStatus',
            fields=[
                ('annual_status_id', models.CharField(default=academic.models.shortuuid, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('teacher', models.CharField(max_length=20)),
                ('yearly_status', models.IntegerField()),
                ('yearly_summary', models.CharField(max_length=300)),
                ('subject_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(default=academic.models.shortuuid, editable=False, max_length=6)),
                ('course_code', models.CharField(default=academic.models.course_custom_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=70)),
                ('effective_date', models.DateField()),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.department')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlySubjectSyllabusStatus',
            fields=[
                ('month_status_id', models.CharField(default=academic.models.shortuuid, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('month', models.DateField()),
                ('status', models.IntegerField()),
                ('monthly_summary', models.CharField(max_length=300)),
                ('annual_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.annuallysubjectsyllabusstatus')),
            ],
        ),
        migrations.CreateModel(
            name='SyllabusStatusVerification',
            fields=[
                ('status_verification_id', models.CharField(default=academic.models.shortuuid, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('feedback', models.TextField(blank=True, max_length=300, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_date', models.DateTimeField()),
                ('monthly_Syllabus_approval', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.monthlysubjectsyllabusstatus')),
            ],
        ),
    ]
