# Generated by Django 5.0.4 on 2024-05-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_department_remove_subject_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='syllabus_count',
            field=models.IntegerField(default=0),
        ),
    ]
