# Generated by Django 5.0.6 on 2024-06-30 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_alter_annuallysubjectsyllabusstatus_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysubjectsyllabusstatus',
            name='annual_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.annuallysubjectsyllabusstatus'),
        ),
        migrations.AlterField(
            model_name='syllabusstatusverification',
            name='monthly_syllabus_approval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.monthlysubjectsyllabusstatus'),
        ),
    ]
